name: Build NineLS

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: waruhachi/theos-action@v2.4.6
        with:
          theos-src: waruhachi/theos
          theos-branch: main
          sdks-src: waruhachi/sdks
          sdks-branch: main
          libgcuniversal: true
          libgcuniversal-src: waruhachi/LibGcUniversal
          libgcuniversal-branch: main

      - name: Build NineLS
        run: |
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: NineLS-deb
          path: packages/*.deb
